# Generated by Django 2.0 on 2019-01-17 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190115_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_image',
            new_name='image',
        ),
    ]
