# Generated by Django 2.0 on 2019-01-21 22:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190117_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('image', models.FileField(blank=True, default='default/images.jpg', null=True, upload_to='', verbose_name='Makaleye Resim Ekle')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, default='default/images.jpg', null=True, upload_to='', verbose_name='Makaleye Resim Ekle'),
        ),
    ]
