# Generated by Django 2.0 on 2019-01-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190122_0118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
